[package]
name = "rust_mongo_bench"
version = "0.1.0"
authors = ["zhangwei217245 <zhangwei217245@gmail.com>"]

[dependencies]
bson = "0.10.0"
mongodb = "0.3.7"


[lib]
name = "rust_mongo_bench"
crate-type = ["dylib"]
