[package]
name = "rust_mongo_bench"
version = "0.1.0"
authors = ["zhangwei217245 <zhangwei217245@gmail.com>"]

[dependencies]
libc = "0.2"
bson = "0.13.0"
mongodb = "0.3.12"
serde_json = "1.0"
lazy_static = "1.0"



[lib]
name = "rust_mongo_bench"
crate-type = ["dylib"]
